### PR TITLE
Svn test sinistro branch syncup

### PR DESCRIPTION
**Pull request by talister**

### CODE REVIEW

**Comment by timj** [comment]
Would be better if all those fake merges were not included in the commit history.

**Comment by timj** [comment]
@MalcolmCurrie are you looking at this PR? I'm happy to merge it soon.

**Comment by talister** [comment]
On 11/03/2015 09:12 AM, Tim Jenness wrote:
> @MalcolmCurrie <https://github.com/MalcolmCurrie> are you looking at
> this PR? I'm happy to merge it soon.

I wouldn't go to too much effort, as of this morning it has be decreed 
that we're abandoning ORAC-DR for the LCOGT pipeline.

>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Starlink/ORAC-DR/pull/17#issuecomment-153421067>.
>


-- 
Dr Tim Lister
Astronomer and Project Scientist
Las Cumbres Observatory (LCOGT.net)
+1 805 880 1989

**Comment by timj** [comment]
Do you want an LSST pipeline? :smile:

**Comment by timj** [comment]
I'll merge this then.

**Pull request merged**
